(()=>{
const path=location.pathname;
const base=path.includes('/growfarmers/')?'/growfarmers/':'/';
const rel=path.startsWith(base)?path.slice(base.length):path.replace(/^\//,'');
const current=rel.startsWith('about/')?'about':rel.startsWith('service/')?'service':rel.startsWith('portfolio/')?'portfolio':rel.startsWith('farms/')?'farms':rel.startsWith('book/')?'book':rel.startsWith('news/')?'news':rel.startsWith('how-we-work/')?'how':rel.startsWith('contact/')?'contact':'';
const nav=[['about','그로우파머스','about/'],['service','우리가 하는 일','service/'],['portfolio','포트폴리오','portfolio/'],['farms','농장과 브랜드','farms/'],['book','농부책방','book/'],['news','뉴스','news/'],['how','함께 일하는 방법','how-we-work/']];
const navMarkup=nav.map(([key,label,href])=>`<a${current===key?' aria-current="page"':''} href="${base}${href}">${label}</a>`).join('');
const mobileMarkup=nav.map(([key,label,href])=>`<a${current===key?' aria-current="page"':''} href="${base}${href}">${label}</a>`).join('');
const header=document.querySelector('.site-header');
if(header){header.outerHTML=`<header class="site-header"><div class="shell header-inner"><a class="brand" href="${base}">GROW FARMERS</a><nav class="desktop-nav">${navMarkup}</nav><div class="header-actions"><a class="header-contact" href="${base}contact/">함께하기</a><a class="cta" href="${base}farms/#register">농장 등록하기</a><button class="menu-button" aria-label="메뉴 열기" aria-expanded="false"><span></span><span></span></button></div></div></header>`;}
const oldMobile=document.querySelector('.mobile-menu');
if(oldMobile){oldMobile.outerHTML=`<div class="mobile-menu">${mobileMarkup}<a href="${base}contact/">함께하기</a><a class="cta" href="${base}farms/#register">농장 등록하기</a></div>`;}
const menuButton=document.querySelector('.menu-button');const mobileMenu=document.querySelector('.mobile-menu');if(menuButton&&mobileMenu){menuButton.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('is-open');menuButton.setAttribute('aria-expanded',String(open));});}
const read=(key)=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};const write=(key,data)=>localStorage.setItem(key,JSON.stringify(data));
const farmForm=document.getElementById('farmRegisterForm');if(farmForm){farmForm.addEventListener('submit',e=>{e.preventDefault();if(!farmForm.reportValidity())return;const fd=new FormData(farmForm);const rows=read('growfarmers_farm_registrations');rows.unshift({id:'farm_'+Date.now(),farmName:String(fd.get('farmName')||''),ownerName:String(fd.get('ownerName')||''),region:String(fd.get('region')||''),phone:String(fd.get('phone')||''),products:String(fd.get('products')||''),season:String(fd.get('season')||''),story:String(fd.get('story')||''),needs:fd.getAll('needs'),status:'접수',createdAt:new Date().toISOString()});write('growfarmers_farm_registrations',rows);farmForm.reset();document.getElementById('farmRegisterSuccess')?.classList.add('show');});}
const contactForm=document.getElementById('contactForm');if(contactForm){contactForm.addEventListener('submit',e=>{e.preventDefault();if(!contactForm.reportValidity())return;const fd=new FormData(contactForm);const rows=read('growfarmers_inquiries');rows.unshift({id:'inq_'+Date.now(),name:String(fd.get('name')||''),phone:String(fd.get('phone')||''),company:String(fd.get('company')||''),email:String(fd.get('email')||''),type:String(fd.get('type')||''),message:String(fd.get('message')||''),status:'신규',createdAt:new Date().toISOString()});write('growfarmers_inquiries',rows);contactForm.reset();document.getElementById('contactSuccess')?.classList.add('show');});}
const projectSummaries={
'01':'스틱형 벌꿀 제품이 가진 간편함과 꿀의 따뜻한 이미지를 함께 살린 선물형 브랜드 디자인입니다. 밝은 옐로우 컬러와 화이트 여백을 중심으로 벌꿀의 달콤함은 선명하게 보여주고, 패키지 전체는 깨끗하고 정돈된 선물 이미지로 전개했습니다. 단상자, 스틱파우치, 쇼핑백, 카드 엽서까지 같은 비주얼 흐름으로 연결해 제품을 하나의 선물 세트처럼 구성했습니다.',
'04':'다양한 젓갈 제품이 가진 진한 감칠맛과 바다의 신선한 이미지를 보다 가볍고 감각적인 방식으로 풀어낸 로컬 브랜드 디자인입니다. 씨앗젓갈, 오징어젓, 낙지젓, 명란젓처럼 서로 다른 제품들을 하나의 브랜드 안에서 정리하기 위해 컬러가 구분되는 라벨 시스템과 부드러운 핑크 톤의 브랜드 무드를 중심으로 전개했습니다. 제품 패키지부터 보냉백과 행사 연출물까지 같은 시각 흐름으로 연결해 젓갈 브랜드를 더 친근하고 세련된 식탁 경험으로 보이도록 구성했습니다.',
'07':'국산 생강이 가진 따뜻한 이미지와 건강한 인상을 차분한 프리미엄 패키지로 정리한 브랜드 디자인입니다. 생강청 제품의 성격에 맞춰 베이지와 골드 계열을 중심으로 부드럽고 안정된 분위기를 만들었고, 병 제품과 선물세트 구성이 함께 어우러지도록 통일감 있게 전개했습니다. 원물의 신뢰감과 선물용 제품의 품격이 함께 느껴지도록 구성한 작업입니다.',
'09':'진천 대추와 노루궁뎅이버섯을 활용한 건강즙 제품을 밝고 친근한 이미지로 풀어낸 브랜드 디자인입니다. 대추 캐릭터와 버섯 캐릭터를 중심으로 제품의 원료를 쉽게 이해할 수 있도록 구성했고, 크림 컬러와 따뜻한 브라운 톤을 사용해 부드럽고 건강한 인상을 만들었습니다. 박스 패키지, 스틱파우치, 시음 행사물까지 같은 캐릭터와 그래픽 흐름으로 연결해 제품을 더 쉽고 즐겁게 경험할 수 있도록 전개했습니다.',
'10':'김치가 가진 선명한 색감과 신선한 재료의 이미지를 직관적으로 보여주는 냉장 식품 패키지 디자인입니다. 포기김치, 맛김치, 나박김치, 깍두기, 총각김치처럼 다양한 김치 제품을 하나의 라벨 구조로 정리하고, 제품별 사진과 붉은 포인트 컬러를 활용해 매대에서 빠르게 구분될 수 있도록 구성했습니다. 투명 용기를 통해 김치의 상태가 바로 보이도록 하고, 라벨은 정보 전달과 식욕을 돋우는 이미지가 함께 살아나도록 전개했습니다.',
'13':'보리굴비가 가진 고급 식재료의 이미지와 정성스러운 선물성을 흰색 패키지 중심으로 정리한 브랜드 디자인입니다. 제품의 특징을 과하게 꾸미기보다 생선 일러스트와 넓은 여백을 활용해 정갈하고 깨끗한 인상을 만들었습니다. 선물상자, 개별 패키지, 쇼핑백, 진열 POP까지 같은 시각 흐름으로 연결해 프리미엄 수산 선물세트의 품격이 자연스럽게 전달되도록 구성했습니다.',
'14':'진천 사과가 가진 상큼하고 달콤한 이미지를 밝고 친근한 식품 패키지로 풀어낸 브랜드 디자인입니다. 사과주스와 사과잼 제품을 함께 전개하면서, 귀여운 사과 캐릭터와 부드러운 크림 컬러를 중심으로 가족이 함께 즐길 수 있는 건강한 간식 이미지를 만들었습니다. 손잡이형 선물상자, 파우치, 유리병 라벨까지 같은 그래픽 흐름으로 연결해 제품군 전체가 하나의 브랜드로 보이도록 구성했습니다.',
'16':'고시히카리, 신동진, 쌀부자처럼 서로 다른 쌀 품종을 차분한 톤으로 정리한 로컬 쌀 패키지 디자인입니다. 쌀이 가진 깨끗하고 담백한 이미지를 살리기 위해 종이 질감이 느껴지는 포장재와 낮은 채도의 컬러를 중심으로 구성했습니다. 품종별로 컬러를 나누되 전체 레이아웃은 통일해 매대에 함께 진열되었을 때 정돈된 브랜드 이미지가 보이도록 전개했습니다.',
'17':'진천을 대표하는 로컬 디저트의 고소하고 따뜻한 이미지를 밝은 옐로우 컬러로 풀어낸 패키지 디자인입니다. 검은콩과 콩 원료가 가진 담백한 맛을 디저트의 형태와 함께 보여주고, 선물상자와 쇼핑백, 안내 카드까지 같은 컬러와 로고 흐름으로 연결했습니다. 매장에서 구매하거나 선물로 전달할 때 모두 밝고 기억에 남는 디저트 브랜드로 보이도록 구성했습니다.',
'20':'섬야초가 가진 자연스러운 향과 맑은 차의 이미지를 차분한 건강식품 패키지로 정리한 브랜드 디자인입니다. 딥그린 컬러를 중심으로 잎과 산의 흐름을 담은 그래픽을 전개해 원물의 깨끗함과 자연에서 온 건강한 인상을 함께 보여주었습니다. 단상자와 스틱파우치를 같은 컬러와 일러스트 흐름으로 연결해 일상에서 가볍게 마실 수 있는 건강차 제품으로 구성했습니다.',
'22':'소금이 가진 깨끗하고 본질적인 이미지를 블랙과 화이트 컬러의 대비로 정리한 프리미엄 패키지 디자인입니다. 유리병, 파우치, 선물상자 구성을 함께 전개하면서 제품의 순수함과 선물 제품으로서의 고급스러운 인상이 동시에 느껴지도록 구성했습니다. 어두운 패키지 위에 작은 소금 이미지와 얇은 선 그래픽을 더해 과하지 않지만 깊이 있는 브랜드 분위기를 만들었습니다.',
'24':'빨간 약호박이 가진 진한 색감과 건강한 이미지를 따뜻하고 밝은 건강즙 패키지로 풀어낸 브랜드 디자인입니다. 오렌지와 옐로우 컬러를 중심으로 호박밭을 떠올리게 하는 일러스트를 적용해 원물의 신선함과 부드러운 맛이 함께 전달되도록 구성했습니다. 손잡이형 선물상자와 파우치, 시음 연출물까지 같은 비주얼 흐름으로 연결해 구매와 선물, 체험까지 이어지는 제품 경험을 만들었습니다.',
'25':'곶감이 가진 진한 주황빛과 쫀득한 식감을 프리미엄 선물 패키지로 정리한 브랜드 디자인입니다. 선명한 오렌지 컬러를 중심으로 제품의 달콤함과 따뜻한 이미지를 강조했고, 투명 트레이와 띠지 구성을 통해 곶감의 형태와 품질이 잘 보이도록 구성했습니다. 선물상자와 쇼핑백까지 같은 컬러로 연결해 구매 후 전달되는 순간까지 강한 브랜드 인상이 이어지도록 전개했습니다.',
'26':'피라미드 형태의 플레이크 솔트가 가진 투명하고 깨끗한 이미지를 화이트 패키지로 정리한 디자인입니다. 과한 장식보다 소금 결정 이미지와 절제된 타이포를 중심으로 구성해 요리에 사용하는 고급 식재료의 인상을 만들었습니다. 제품의 순수함과 사용 장면이 자연스럽게 연결되도록 소금, 그릇, 조리 장면을 함께 연출했습니다.',
'27':'사과와 샤인머스캣이 가진 상큼하고 깨끗한 이미지를 밝은 그린 컬러 중심의 주스 패키지로 정리한 디자인입니다. 과일을 꼬치처럼 쌓은 비주얼을 전면에 배치해 두 원료의 조합이 직관적으로 보이도록 했고, 스파우트 파우치와 단상자를 같은 구조로 연결해 제품의 신선하고 간편한 이미지를 함께 보여주었습니다. 전체적으로 가볍게 마실 수 있는 로컬 과일주스의 산뜻한 인상을 만들었습니다.',
'28':'유정란이 가진 신선하고 건강한 이미지를 부드러운 그린 컬러와 숲 일러스트로 정리한 패키지 디자인입니다. 회색 펄프 난좌가 가진 자연스러운 질감을 살리고, 중앙 슬리브에는 나무와 들판 이미지를 넣어 농장에서 온 깨끗한 먹거리라는 인상을 만들었습니다. 전체적으로 과하게 꾸미기보다 담백하고 편안한 분위기로 제품의 신뢰감을 전달했습니다.',
'29':'국내산 자연 농수산물을 활용한 천연 조미료의 이미지를 베이지와 화이트 중심의 패키지로 정리한 디자인입니다. 멸치, 새우, 다시마, 표고버섯, 마늘 등 원료 이미지를 선 일러스트로 표현해 제품의 자연스러운 원료감을 보여주었고, 스틱 파우치 구조를 통해 조리 과정에서 간편하게 사용할 수 있는 제품 특징을 함께 전달했습니다. 전체적으로 자극적인 조미료 이미지보다 담백하고 정돈된 주방용 식품의 인상을 만들었습니다.',
'31':'바다찬빛은 건멸치가 가진 신선함과 담백한 이미지를 과장하지 않고, 깨끗한 화이트 패키지 안에 정돈해 보여준 선물세트 디자인입니다. 제품의 핵심인 멸치는 투명 파우치를 통해 직접 보이도록 구성했고, 외부 박스에는 흑백 멸치 일러스트와 작은 붉은 인장을 배치해 전통적인 식재료의 신뢰감을 더했습니다. 전체적으로 장식 요소를 줄이고 여백을 넓게 사용해 건어물 제품이 가진 청결함, 품질감, 선물성을 차분하게 전달했습니다.',
'34':'자담인 홍삼 엑기스는 홍삼 원료가 가진 진한 농도감과 프리미엄 건강식품의 이미지를 시각적으로 전달하기 위해 딥 레드와 블랙 컬러를 중심으로 구성한 패키지 디자인입니다. 붉은 배경은 홍삼의 따뜻한 에너지와 원료의 깊이를 보여주고, 블랙 라벨 영역은 제품명을 또렷하게 부각해 고급스러운 인상을 만듭니다. 단상자와 스틱 파우치에 같은 컬러 구조와 식물 그래픽을 반복 적용해 제품 전체가 하나의 브랜드 세트처럼 정돈되어 보이도록 했습니다.',
'36':'FROZEN COOKED OYSTER는 냉동 수산물이 가져야 할 차가운 신선함과 보관 안정성을 시각적으로 보여주는 패키지 디자인입니다. 상단의 선명한 블루 컬러는 바다와 냉동 보관 이미지를 직접적으로 연결하고, 양쪽의 실버 파우치 재질은 저온 유통 제품의 차갑고 깨끗한 인상을 강화합니다. 중앙에는 굴 원물 이미지를 크게 배치해 제품의 종류를 빠르게 인식할 수 있도록 했으며, 얼음과 물방울 연출은 냉동 제품의 신선한 상태를 강조합니다.'
};
const projects=[
['01','스틱형 벌꿀의 밝은 선물성을 담은 브랜드 디자인',['gift','food','local']],['02','홍삼과 배의 깊이를 정갈하게 담은 선물 브랜드 디자인',['gift','health','local']],['03','지역 식재료의 건강한 식탁 이미지를 담은 브랜드 디자인',['food','local']],['04','바다의 감칠맛을 친근한 프리미엄 식탁 브랜드로 풀어낸 디자인',['food','local']],['05','전통 풍경을 현대적으로 풀어낸 프리미엄 선물 브랜드 디자인',['gift','health']],['06','콩과 메주의 담백함을 정갈하게 담은 패키지 디자인',['gift','food','local']],['07','생강의 온기를 부드럽고 정갈한 선물 이미지로 담은 패키지 디자인',['gift','health','local']],['08','흑삼의 깊이를 블랙 무드로 표현한 프리미엄 선물 패키지 디자인',['gift','health']],['09','대추와 노루궁뎅이버섯을 친근하게 풀어낸 건강즙 브랜드 디자인',['health','local']],['10','신선한 김치의 색감과 시원한 맛을 살린 패키지 디자인',['food','local']],['11','홍삼의 깊은 인상을 고급 선물세트로 담은 패키지 디자인',['gift','health']],['12','지리산의 자연 이미지를 밝게 담은 스틱꿀 선물세트 디자인',['gift','food','local']],['13','보리굴비의 정갈한 품격을 흰 여백에 담은 선물 패키지 디자인',['gift','food','local']],['14','사과의 밝은 맛을 친근하게 담은 패키지 디자인',['food','local']],['15','우리쌀 간식의 담백함을 따뜻하게 담은 패키지 디자인',['food','local']],['16','쌀의 담백함을 자연스럽게 담은 품종별 패키지 디자인',['food','local']],['17','로컬 디저트의 고소한 맛을 밝게 담은 패키지 디자인',['gift','food','local']],['18','흑홍삼절편의 깊은 기운을 전통 풍경으로 담은 패키지 디자인',['gift','health']],['19','잡곡의 균형을 간편하게 담은 보약잡곡 패키지 디자인',['food','health','local']],['20','섬야초의 맑은 기운을 차분하게 담은 스틱차 패키지 디자인',['health','local']],['21','호박과 팥의 따뜻함을 담은 티백차 패키지 디자인',['food','health','local']],['22','소금의 순수함을 절제된 고급감으로 담은 패키지 디자인',['gift','food']],['23','재래맛김의 깨끗한 풍미를 담은 선물 패키지 디자인',['gift','food','local']],['24','빨간 약호박의 진한 색감을 밝게 담은 건강즙 패키지 디자인',['health','local']],['25','곶감의 달콤한 색감을 선명하게 담은 선물 패키지 디자인',['gift','food','local']],['26','소금 결정의 깨끗함을 미니멀하게 담은 패키지 디자인',['food']],['27','사과와 샤인머스캣의 산뜻함을 담은 주스 패키지 디자인',['food','local']],['28','숲의 편안함으로 유정란의 건강한 이미지를 전하다',['food','local']],['29','담백한 베이지 톤으로 천연 조미료의 신뢰를 정리하다',['food','local']],['30','지리산의 계절을 담은 프리미엄 허니 선물세트 디자인',['gift','food','local']],['31','깨끗한 바다의 맛을 정갈하게 담은 건멸치 선물세트 디자인',['gift','food','local']],['32','아이보리와 딥 레드 컬러로 매일 챙기는 홍삼 루틴을 만들다',['health']],['33','크림 톤 패키지와 투명 용기로 정갈한 새우젓의 신선함을 담다',['food','local']],['34','딥 레드와 블랙 컬러로 홍삼 엑기스의 깊은 인상을 만들다',['gift','health']],['35','화이트와 브라운 컬러로 신선한 냉장 버섯의 신뢰감을 만들다',['food','local']],['36','블루 컬러와 실버 파우치로 냉동 굴의 신선함을 직관적으로 전달하다',['food','local']]
].map(([n,title,tags])=>({n,title,tags,summary:projectSummaries[n]||'농산물과 로컬 상품의 특징을 시장에서 이해하기 쉬운 브랜드와 패키지 언어로 정리한 프로젝트입니다.'}));
const grid=document.getElementById('projectGrid');const count=document.getElementById('portfolioCount');const tagNames={gift:'선물세트',food:'식품',health:'건강식품',local:'로컬 브랜드'};const imgBase='../assets/projects/';const importedCovers=new Set(['01','04','07','09','10','13','14','16','17','20','22','24','25','26','27','28','29','31','34','36']);const coverPath=p=>`${imgBase}${p.n}.${importedCovers.has(p.n)?'png':'jpg'}`;function render(filter='all'){if(!grid)return;const list=projects.filter(p=>filter==='all'||p.tags.includes(filter));if(count)count.textContent=list.length;grid.innerHTML=list.map(p=>`<article class="project-card" data-project="${p.n}"><div class="project-thumb"><img src="${coverPath(p)}" alt="${p.title}" onerror="this.parentElement.classList.add('no-image')"><div class="project-placeholder"><span>GROW FARMERS PROJECT</span><strong>${p.n}</strong><span>이미지 준비 중</span></div></div><div class="project-info"><h3>${p.title}</h3><p>${p.summary}</p><div class="project-tags">${p.tags.map(t=>`<span>${tagNames[t]}</span>`).join('')}</div></div></article>`).join('');grid.querySelectorAll('.project-card').forEach(card=>card.addEventListener('click',()=>openProject(card.dataset.project)));}
if(grid){render();document.querySelectorAll('.work-filter button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.work-filter button').forEach(b=>b.classList.remove('is-active'));btn.classList.add('is-active');render(btn.dataset.filter)}));}
const modal=document.getElementById('projectModal');function openProject(n){if(!modal)return;const p=projects.find(x=>x.n===n);if(!p)return;document.getElementById('projectModalIndex').textContent=`PROJECT ${p.n}`;document.getElementById('projectModalTitle').textContent=p.title;document.getElementById('projectModalSummary').textContent=p.summary;document.getElementById('projectModalTags').innerHTML=p.tags.map(t=>`<span>${tagNames[t]}</span>`).join('');const image=document.getElementById('projectModalImage');image.style.backgroundImage=`url('${coverPath(p)}')`;modal.classList.add('is-open');document.body.style.overflow='hidden';}document.querySelectorAll('[data-close-project]').forEach(el=>el.addEventListener('click',()=>{modal?.classList.remove('is-open');document.body.style.overflow='';}));
})();